apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "fleet.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fleet.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        {{- include "fleet.podAnnotations" . | nindent 8 }}
        {{- with .Values.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "fleet.selectorLabels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ include "fleet.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.container.securityContext.enabled }}
          securityContext: {{- omit .Values.container.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.image.command }}
          command: {{ toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.image.args }}
          args: {{ toYaml .Values.image.args | nindent 12 }}
          {{- end }}
          {{- with .Values.container.env }}
          env: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.container.envFrom }}
          envFrom: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if (or .Values.persistence.enabled .Values.container.extraVolumeMounts) }}
          volumeMounts:
            - name: {{ .Values.persistence.volumeName }}
              mountPath: {{ .Values.persistence.volumeMountPath }}
          {{- end }}
          {{- with .Values.container.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          {{- range $config := .Values.container.ports }}
            - containerPort: {{ $config.containerPort }}
              name: {{$config.name}}
              protocol: {{$config.protocol | default "TCP"}}
          {{- end }}
          livenessProbe:
            {{- with .Values.livenessProbe }}
              {{- toYaml . | nindent 12 }}
            {{- else }}
            httpGet:
              path: /health
              port: 80
              initialDelaySeconds: 10
              periodSeconds: 10
            {{- end }}
          readinessProbe:
            {{- with .Values.readinessProbe }}
              {{- toYaml . | nindent 12 }}
            {{- else }}
            httpGet:
              path: /health
              port: 80
              initialDelaySeconds: 5
              periodSeconds: 5
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if (or .Values.persistence.enabled .Values.pod.extraVolumes) }}
      volumes:
        - name: {{ .Values.persistence.volumeName }}
        {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.pod.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
