apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "fleet.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $config := .Values.container.ports }}
    - name: {{$config.name}}
      port: {{ $config.servicePort | default $config.containerPort }}
      targetPort: {{ $config.containerPort | default $config.name }}
      protocol: {{ $config.protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "fleet.selectorLabels" . | nindent 4 }}
